# Generated by Django 4.1.1 on 2022-10-15 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby_name', models.CharField(max_length=16)),
                ('game_master', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LobbyPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('lobby_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='master.lobby')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_value', models.CharField(max_length=20)),
                ('parameter_id', models.IntegerField()),
                ('player_id', models.IntegerField()),
                ('lobby_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_parameters', to='master.lobby')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateItemName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=1000)),
                ('lobby_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_item_names', to='master.lobby')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateItemModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('modifier_id', models.IntegerField()),
                ('modifier_value', models.CharField(max_length=40, null=True)),
                ('lobby_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_item_modifier', to='master.lobby')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateItemDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('item_description', models.CharField(max_length=1000)),
                ('lobby_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_item_description', to='master.lobby')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateDeleteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('lobby_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_delete_items', to='master.lobby')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateCreateItemModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('lobby_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_create_item_modifier', to='master.lobby')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateCreateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('lobby_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_create_items', to='master.lobby')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_value', models.CharField(default='', max_length=20)),
                ('parameter_id', models.IntegerField()),
                ('player_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='master.lobbyplayer')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='PlayerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(default='', max_length=20)),
                ('item_description', models.CharField(default='', max_length=1000)),
                ('player_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='master.lobbyplayer')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='LobbyParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=20, null=True)),
                ('parameter_stat', models.CharField(max_length=10, null=True)),
                ('parameter_formula', models.CharField(max_length=30, null=True)),
                ('parameter_id', models.IntegerField()),
                ('lobby_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_parameters', to='master.lobby')),
            ],
        ),
        migrations.CreateModel(
            name='ItemModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier_id', models.IntegerField()),
                ('modifier_value', models.CharField(max_length=40, null=True)),
                ('item_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='master.playeritem')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
