# Generated by Django 4.1.1 on 2022-09-26 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='LobbyManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LobbyParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_field', models.CharField(max_length=60, null=True)),
                ('lobby_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_parameters', to='master.lobby')),
            ],
        ),
    ]
