# Generated by Django 4.1.1 on 2022-10-05 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby_name', models.CharField(max_length=16)),
                ('game_master', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LobbyPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('lobby_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='master.lobby')),
            ],
        ),
        migrations.CreateModel(
            name='UpdatedParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=1000)),
                ('parameter_id', models.IntegerField()),
                ('player_id', models.IntegerField()),
                ('lobby_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_parameters', to='master.lobby')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_parameter', models.CharField(default='', max_length=1000)),
                ('parameter_id', models.IntegerField()),
                ('player_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_parameters', to='master.lobbyplayer')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='LobbyParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_field', models.CharField(max_length=60, null=True)),
                ('lobby_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_parameters', to='master.lobby')),
            ],
        ),
    ]
