# Generated by Django 3.2.16 on 2022-11-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobbyparameter',
            name='parameter_formula',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='lobbyparameter',
            name='parameter_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lobbyparameter',
            name='parameter_stat',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
